FROM almalinux:9

ENV TZ="{{ timezone_output.stdout }}"
ENV DISCORD_TOKEN="{{ discord_token }}"
ENV PYTHONPATH="."

RUN dnf install python39 git -y
RUN mkdir -p /code/sources
WORKDIR /code
  COPY prod.txt sources/prod.txt
RUN python3.9 -m venv --system-site-packages --symlinks venv
RUN python3.9 -m ensurepip -U
RUN source venv/bin/activate && pip install -r sources/prod.txt
ENTRYPOINT ["venv/bin/python3", "sources/main.py"]
