FROM almalinux:10

ENV PYTHONPATH="."

RUN dnf install python3 git libpq-devel python3-devel -y
RUN dnf group install 'Development Tools' -y
RUN mkdir -p /code/sources
WORKDIR /code
COPY prod.txt sources/prod.txt
RUN python3 -m venv --symlinks venv
RUN source venv/bin/activate && python3 -m pip install pip -U && pip install -r sources/prod.txt
ENTRYPOINT ["bash"]