---
- name: Get current timezone
  ansible.builtin.command: timedatectl show --property=Timezone --value
  register: timezone_output
  changed_when: false

- name: Get existing of a docker network
  community.docker.docker_network_info:
    name: "{{ docker_network }}"
  register: docker_network_result

- name: Add a separate docker network
  community.docker.docker_network:
    name: "{{ docker_network }}"
  when: not docker_network_result.exists

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: docker_temp_directory

- name: Working in a build directory
  block:
    - name: Prepare Dockerfile
      ansible.builtin.template:
        dest: "{{ docker_temp_directory.path }}/Dockerfile"
        src: "Dockerfile.j2"

    - name: Create volume directory for a container
      ansible.builtin.file:
        path: "{{ docker_lib_folder }}/{{ item.value.path }}"
        recurse: yes
        state: directory
      become: yes
      loop: "{{ docker_volumes | dict2items }}"

    - name: Copy req.txt for building a docker image
      ansible.builtin.copy:
        dest: "{{ docker_temp_directory.path }}/prod.txt"
        src: "../../../../sources/prod.txt"

    - name: Copy sources
      ansible.posix.synchronize:
        dest: "{{ docker_lib_folder }}/{{ docker_volumes['sources']['path'] }}"
        src: "../../../../sources/"
        owner: false
        group: false
      become: yes
      register: sources_result

    - name: Build a docker image
      community.docker.docker_image:
        name: "discord-meow-bot"
        force_source: yes
        build:
          path: "{{ docker_temp_directory.path }}"
          pull: yes
          network: host
        source: build
      become: yes

    - name: Up a docker container with the bot
      community.docker.docker_container:
        name: "discord-meow-bot"
        image: "discord-meow-bot"
        state: started
        restart: "{{ sources_result.changed }}"
        restart_policy: always
        command:
          - "-c"
          - >-
            venv/bin/python3 sources/scripts/create_db.py &&
            venv/bin/alembic -c sources/alembic.ini upgrade head &&
            venv/bin/python3 sources/scripts/main.py
        mounts:
          - source: "{{ docker_lib_folder }}/{{ docker_volumes['sources']['path'] }}"
            target: "/code/sources"
            read_only: yes
            type: bind
          - source: "{{ docker_lib_folder }}/{{ docker_volumes['images']['path'] }}"
            target: "/code/images"
            read_only: no
            type: bind
        networks:
          - name: "{{ docker_network }}"
        env:
          DISCORD_TOKEN: "{{ discord_token }}"
          BIRTHDAY_IMAGES_DIR: "/code/images"
          YOUTUBE_API_KEY: "{{ youtube_api_key }}"
          SPOTIFY_API_CLIENT_ID: "{{ spotify_api_client_id }}"
          SPOTIFY_API_CLIENT_SECRET: "{{ spotify_api_client_secret }}"
          LASTFM_API_KEY: "{{ lastfm_api_key }}"
          DB_LOGIN: "{{ db_login }}"
          DB_PASSWORD: "{{ db_password }}"
          DB_HOST: "{{ db_host }}"
          DB_DATABASE: "{{ db_database }}"
          DB_PORT: "{{ db_port | string }}"
        log_driver: journald
      become: yes

  always:
    - name: Remove temp build directory
      ansible.builtin.file:
        path: "{{ docker_temp_directory.path }}"
        state: absent
...
