FROM almalinux:9
RUN dnf install python39 -y
RUN mkdir -p /code
WORKDIR /code
RUN python3.9 -m venv --system-site-packages --symlinks venv
COPY /sources/* .
RUN source venv/bin/activate && pip install -r req.txt
ENV DISCORD_TOKEN="{{ discord_token }}"
ENTRYPOINT ["venv/bin/python3", "main.py"]
