FROM almalinux:9
ENV TZ="{{ timezone_output.stdout }}"
RUN dnf install python39 git -y
RUN mkdir -p /code/sources
WORKDIR /code
COPY req.txt sources/req.txt
RUN python3.9 -m venv --system-site-packages --symlinks venv
RUN source venv/bin/activate && pip install -r sources/req.txt
ENV DISCORD_TOKEN="{{ discord_token }}"
ENTRYPOINT ["venv/bin/python3", "sources/main.py"]
