---
discord_token: "{{ lookup('bitwarden.secrets.lookup', '76922d91-098e-4b58-b669-b4310084be27') }}"
db_password: "{{ lookup('bitwarden.secrets.lookup', 'c3f44971-a7af-4b62-af36-b4310084dcc0') }}"
db_login: "meow-bot"
db_host: postgresql
db_port: 5432
db_database: "meow-bot"
...
